"""Extract the deployed notebook's post-processing into an importable module.

The kernel keeps its prediction .geff files, and 8 of them are TRAIN films, so
we hold deployed-quality graphs (adj_J 0.926) WITH ground truth. Port the
notebook's own post-processing and every parameter becomes a seconds-long local
experiment instead of a ~1.75 hour Kaggle run.

Takes only top-level defs/classes/assignments. Anything that executes at import
time -- pip installs, model loading, inference, submission writing -- is left
behind.
"""
import ast, json
from pathlib import Path

nb = json.loads(Path("Public Notebooks/biohub-0-947-lb-runnable-with-public-datasets.ipynb").read_text())
src = "".join(nb["cells"][2]["source"])
tree = ast.parse(src)

keep, skipped = [], []
for node in tree.body:
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef,
                         ast.Import, ast.ImportFrom)):
        keep.append(node)
    elif isinstance(node, (ast.Assign, ast.AnnAssign)):
        # keep only assignments with no function call on the right-hand side,
        # except the os.environ.get / float / int config reads we need
        rhs = ast.dump(node.value) if node.value else ""
        risky = any(t in rhs for t in ("subprocess", "torch.load", "predict",
                                       "materialize", "ensure_dependencies",
                                       "find_artifacts", "Popen", "check_output"))
        (skipped if risky else keep).append(node)
    else:
        skipped.append(node)

mod = ast.Module(body=keep, type_ignores=[])
code = ast.unparse(mod)
out = Path("src/biohub/deployed_pp.py")
out.write_text('"""Post-processing lifted verbatim from the deployed 0.947 notebook.\n\n'
               'Generated by scripts/21_extract_pp.py -- do not edit by hand.\n'
               'Only top-level definitions were taken; nothing that executes at import.\n"""\n'
               + code + "\n")
print(f"kept {len(keep)} top-level nodes, skipped {len(skipped)}")
print(f"wrote {out}  ({len(code):,} chars)")
fns = [n.name for n in keep if isinstance(n, ast.FunctionDef)]
print(f"\n{len(fns)} functions, including:")
for f in ("filter_output_graph", "motion_relink_edges", "close_single_frame_gaps",
          "recover_strict_gap2", "add_safe_divisions", "filter_short_tracks",
          "match_nodes_bipartite", "compute_division_confusion", "score_sample",
          "aggregate_official", "graph_from_geff", "read_test_frame"):
    print(f"  {'OK ' if f in fns else 'MISSING'} {f}")
