"""A diagnostic kernel that measures the Kaggle runtime and touches nothing else.

E03-SMOKE-02 died on ``import zarr``, and one traceback is not enough to build a
wheelhouse from. A wheel has to match the target's Python version, platform tag
and ABI, and none of those have been measured; they have only been inferred.

So this package answers what is actually there. It reads no competition data,
trains nothing, requests no accelerator, and imports no part of Biohub-X, because
a diagnostic that depends on the thing it is diagnosing cannot run when that
thing is missing. Every probe is wrapped: a package that is absent is reported as
absent and the audit continues, since a crash on the first gap would tell us only
about that gap.

The blosc probe is the sharp one. The competition volumes are zarr v3 with a
blosc/zstd/bitshuffle codec at typesize 2, so this carries a small buffer encoded
exactly that way and asks the target to decode it. Importability is not the
question; decoding the real codec is.

Consumer: ``biohubx package audit``.
"""

from __future__ import annotations

import base64
from dataclasses import dataclass
from typing import Any

AUDIT_ID = "E03-ENV-AUDIT-01"
AUDIT_KERNEL = "aryaarun07/biohub-x-environment-audit"
AUDIT_TITLE = "Biohub X environment audit"
AUDIT_RUNTIME_CEILING_SECONDS = 300

RUNTIME_CLOSURE: tuple[str, ...] = (
    # Declared runtime dependencies of biohubx.
    "numpy",
    "pydantic",
    "polars",
    "yaml",
    "scipy",
    "typer",
    "zarr",
    "tracksdata",
    # The model-cpu group.
    "torch",
    # What zarr and tracksdata pull in, and what the competition data needs.
    "numcodecs",
    "blosc2",
    "geff",
    "donfig",
    "bidict",
    "rustworkx",
    "imagecodecs",
    "dask",
    "pyarrow",
    "sqlalchemy",
    "psygnal",
    "numba",
    "skimage",
    "tqdm",
    "typing_extensions",
    "crc32c",
    "packaging",
    "click",
    "annotated_types",
)
"""Every import Biohub-X reaches for at runtime, plus the codec stack beneath it.

Import names, not distribution names, because importability is what fails. The
audit reports distribution versions separately from a full `importlib.metadata`
listing.
"""


class AuditError(ValueError):
    """The audit package could not be built."""


@dataclass(frozen=True, slots=True)
class AuditSpec:
    """What the diagnostic declares about itself."""

    audit_id: str
    commit: str
    kernel: str
    runtime_ceiling_seconds: int

    def to_dict(self) -> dict[str, Any]:
        return {
            "audit_id": self.audit_id,
            "commit": self.commit,
            "kernel": self.kernel,
            "runtime_ceiling_seconds": self.runtime_ceiling_seconds,
        }


def blosc_fixture() -> tuple[str, str]:
    """A buffer encoded with the competition's own codec, and its expected content.

    Built here so the target does not need an encoder to prove it has a decoder.
    Returns the base64 payload and a description of what decoding it should yield.
    """
    try:
        import numpy as np
        from numcodecs import Blosc
    except ImportError as exc:  # pragma: no cover - the build machine has both
        raise AuditError("numcodecs is needed to build the decode fixture") from exc

    codec = Blosc(cname="zstd", clevel=1, shuffle=Blosc.BITSHUFFLE, blocksize=0)
    original = np.arange(256, dtype=np.uint16)
    encoded = codec.encode(original.tobytes())
    return base64.b64encode(encoded).decode("ascii"), "uint16 arange(256)"


def audit_kernel_metadata(kernel: str = AUDIT_KERNEL, title: str = AUDIT_TITLE) -> dict[str, Any]:
    """CPU only, no accelerator, no internet, no sources of any kind.

    A diagnostic that could reach the network would measure a machine nobody will
    train on, and one with data sources attached would risk touching competition
    bytes for no reason.
    """
    return {
        "id": kernel,
        "title": title,
        "code_file": "run.ipynb",
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        "enable_gpu": False,
        "enable_internet": False,
        "dataset_sources": [],
        "kernel_sources": [],
        "model_sources": [],
        "competition_sources": [],
    }


AUDIT_CELL = """\
# Generated by `biohubx package audit`. Do not edit here.
#
# A diagnostic. It reads no competition data, trains nothing, requests no
# accelerator, and imports no part of Biohub-X, because a diagnostic that depends
# on the thing it is diagnosing cannot run when that thing is missing.
#
# Every probe is wrapped. A package that is absent is reported absent and the
# audit continues; stopping at the first gap would measure only that gap.
import base64
import json
import os
import pathlib
import platform
import sys
import time


def stage(name, detail=""):
    print(("BIOHUBX_STAGE " + name + " " + str(detail)).rstrip(), flush=True)


AUDIT = json.loads(r\"\"\"__AUDIT_JSON__\"\"\")
CLOSURE = json.loads(r\"\"\"__CLOSURE_JSON__\"\"\")
BLOSC_FIXTURE_B64 = "__BLOSC_FIXTURE__"

started = time.time()
stage("audit-start", AUDIT["audit_id"] + " commit=" + AUDIT["commit"])

report = {"schema_version": 1, "audit_id": AUDIT["audit_id"], "commit": AUDIT["commit"]}

stage("probe-interpreter", "begin")
report["interpreter"] = {
    "python_version": sys.version,
    "version_info": list(sys.version_info[:3]),
    "implementation": platform.python_implementation(),
    "executable": sys.executable,
    "platform": platform.platform(),
    "system": platform.system(),
    "release": platform.release(),
    "machine": platform.machine(),
    "processor": platform.processor(),
    "architecture": list(platform.architecture()),
    "libc": list(platform.libc_ver()),
    "maxsize": sys.maxsize,
}
try:
    import sysconfig

    report["interpreter"]["platform_tag"] = sysconfig.get_platform()
    report["interpreter"]["abi_flags"] = sysconfig.get_config_var("SOABI")
except Exception as exc:
    report["interpreter"]["platform_tag_error"] = repr(exc)
stage("probe-interpreter", "python=" + platform.python_version() + " platform=" + platform.platform())

stage("probe-distributions", "begin")
try:
    import importlib.metadata as md

    installed = {}
    for dist in md.distributions():
        try:
            name = dist.metadata["Name"]
            if name:
                installed[name] = dist.version
        except Exception:
            continue
    report["installed_distributions"] = dict(sorted(installed.items()))
    stage("probe-distributions", "count=" + str(len(installed)))
except Exception as exc:
    report["installed_distributions_error"] = repr(exc)
    stage("probe-distributions", "failed " + repr(exc))

stage("probe-imports", "begin count=" + str(len(CLOSURE)))
imports = {}
for name in CLOSURE:
    entry = {"importable": False}
    try:
        module = __import__(name)
        entry["importable"] = True
        entry["version"] = str(getattr(module, "__version__", "unknown"))
        entry["file"] = str(getattr(module, "__file__", "unknown"))
    except BaseException as exc:
        entry["error"] = repr(exc)[:300]
    imports[name] = entry
    stage("probe-import", name + " importable=" + str(entry["importable"]))
report["imports"] = imports
missing = sorted(n for n, e in imports.items() if not e["importable"])
report["missing_imports"] = missing
stage("probe-imports", "missing=" + json.dumps(missing))

stage("probe-codec", "begin")
codec = {"fixture_description": "__FIXTURE_DESCRIPTION__"}
try:
    raw = base64.b64decode(BLOSC_FIXTURE_B64)
    codec["fixture_bytes"] = len(raw)
    try:
        import numpy as np
        from numcodecs import Blosc

        decoded = np.frombuffer(
            Blosc(cname="zstd", clevel=1, shuffle=Blosc.BITSHUFFLE, blocksize=0).decode(raw),
            dtype="uint16",
        )
        codec["numcodecs_blosc_decode"] = bool(
            len(decoded) == 256 and int(decoded[0]) == 0 and int(decoded[255]) == 255
        )
    except BaseException as exc:
        codec["numcodecs_blosc_decode_error"] = repr(exc)[:300]
    try:
        import blosc2

        codec["blosc2_version"] = str(getattr(blosc2, "__version__", "unknown"))
    except BaseException as exc:
        codec["blosc2_error"] = repr(exc)[:300]
    try:
        import zarr

        codec["zarr_version"] = str(getattr(zarr, "__version__", "unknown"))
        codec["zarr_has_blosc_codec"] = hasattr(getattr(zarr, "codecs", None), "BloscCodec")
    except BaseException as exc:
        codec["zarr_error"] = repr(exc)[:300]
    try:
        import zstandard

        codec["zstandard_version"] = str(getattr(zstandard, "__version__", "unknown"))
    except BaseException as exc:
        codec["zstandard_error"] = repr(exc)[:200]
except BaseException as exc:
    codec["fixture_error"] = repr(exc)[:300]
report["codec"] = codec
stage("probe-codec", json.dumps({k: v for k, v in codec.items() if isinstance(v, (bool, int, str))})[:200])

stage("probe-torch", "begin")
torch_report = {"present": False}
try:
    import torch

    torch_report = {
        "present": True,
        "version": torch.__version__,
        "cuda_build": torch.version.cuda,
        "cudnn": getattr(torch.backends.cudnn, "version", lambda: None)(),
        "cuda_available": torch.cuda.is_available(),
        "device_count": torch.cuda.device_count(),
    }
except BaseException as exc:
    torch_report["error"] = repr(exc)[:300]
report["torch"] = torch_report
stage("probe-torch", json.dumps({k: v for k, v in torch_report.items() if not isinstance(v, dict)})[:200])

report["elapsed_seconds"] = round(time.time() - started, 3)
out = pathlib.Path(os.environ.get("BIOHUBX_OUTPUT", "/kaggle/working"))
out.mkdir(parents=True, exist_ok=True)
manifest = out / "environment-audit.json"
partial = manifest.with_suffix(".json.partial")
partial.write_text(json.dumps(report, indent=2, sort_keys=True, default=str) + chr(10), encoding="utf-8")
partial.replace(manifest)
stage("manifest", str(manifest) + " bytes=" + str(manifest.stat().st_size))
stage("done", "elapsed=" + str(report["elapsed_seconds"]) + "s missing=" + str(len(missing)))
"""


def build_audit_notebook(spec: AuditSpec) -> dict[str, Any]:
    """One cell, no payload, no Biohub-X import, and the fields nbformat requires."""
    import json

    fixture, description = blosc_fixture()
    source = (
        AUDIT_CELL.replace("__AUDIT_JSON__", json.dumps(spec.to_dict(), sort_keys=True))
        .replace("__CLOSURE_JSON__", json.dumps(list(RUNTIME_CLOSURE)))
        .replace("__BLOSC_FIXTURE__", fixture)
        .replace("__FIXTURE_DESCRIPTION__", description)
    )
    for forbidden in ("import biohubx", "from biohubx", "/kaggle/input"):
        if forbidden in source:
            raise AuditError(f"the audit notebook must not contain {forbidden!r}")
    return {
        "cells": [
            {
                "id": "biohubx-environment-audit",
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": source.splitlines(keepends=True),
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


EXPECTED_AUDIT_STAGES: tuple[str, ...] = (
    "audit-start",
    "probe-interpreter",
    "probe-distributions",
    "probe-imports",
    "probe-import",
    "probe-codec",
    "probe-torch",
    "manifest",
    "done",
)
"""What a healthy audit announces. Absent packages are reported, not fatal."""
