"""Does the metric wheelhouse install on the target, and does the scorer there agree with the scorer here.

The zarr preflight asked whether a wheelhouse installs and reads a chunk. This
one asks the question a fold cannot afford to discover at its end: that the
official metric, assembled from thirteen wheels on an image Biohub-X did not
build, imports strictly, is the pinned source byte for byte, characterises its
fixtures as it does locally, and scores a real window to the same numbers.

The notebook carries the package the way the training kernel does, because the
checks import Biohub-X; what runs on the target is
:mod:`biohubx.packaging.metric_preflight_runtime`, and the baseline it compares
against travels in the spec, computed on this machine before the push.

Consumer: ``biohubx package metric-preflight``.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

from biohubx.packaging.kaggle import (
    DEFAULT_PACKAGE_ROOT,
    PackagingError,
    check_payload_contents,
    encode_payload,
    slug_of,
)
from biohubx.packaging.preflight import INPUT_ROOT_DEFAULT, TREE_VERIFIER_SOURCE

METRIC_PREFLIGHT_ID = "E06-METRIC-PREFLIGHT-01"
METRIC_PREFLIGHT_KERNEL = "aryaarun07/biohub-x-metric-preflight"
METRIC_PREFLIGHT_TITLE = "Biohub X metric preflight"
METRIC_WHEELHOUSE_SLUG = "aryaarun07/biohubx-wheelhouse-metric-cp312-linux"
METRIC_PREFLIGHT_RUNTIME_CEILING_SECONDS = 900
"""Fifteen minutes. The install is 123 MiB of wheels, the fixtures take seconds,
and the real-data window is two frames of one movie; the ceiling is generous so
a slow mount reads as slow rather than as a failure."""

EXPECTED_METRIC_PREFLIGHT_STAGES: tuple[str, ...] = (
    "bootstrap-verify",
    "bootstrap-extract",
    "wheelhouse",
    "wheelhouse-verify",
    "wheelhouse-install",
    "bootstrap-import",
    "preflight-start",
    "imports",
    "official-source",
    "fixtures",
    "equivalence",
    "real-data",
    "manifest",
    "done",
)


def metric_preflight_kernel_metadata(
    kernel: str = METRIC_PREFLIGHT_KERNEL, title: str = METRIC_PREFLIGHT_TITLE
) -> dict[str, Any]:
    """CPU, no internet, the metric wheelhouse and the competition, nothing else.

    The competition is attached for one two-frame window of one movie, which is
    the real-data score; without it the preflight would prove agreement only on
    synthetic graphs. No GPU, because nothing here trains.
    """
    owner, _, name = kernel.rpartition("/")
    if not owner:
        raise PackagingError(f"a Kaggle kernel id is owner/slug; got {kernel!r}")
    if slug_of(title) != name:
        raise PackagingError(
            f"title {title!r} slugifies to {slug_of(title)!r}, not {name!r}; Kaggle would create a "
            "kernel at a different address than the one named"
        )
    return {
        "id": kernel,
        "title": title,
        "code_file": "run.ipynb",
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        "enable_gpu": False,
        "enable_internet": False,
        "dataset_sources": [METRIC_WHEELHOUSE_SLUG],
        "kernel_sources": [],
        "model_sources": [],
        "competition_sources": ["biohub-cell-tracking-during-development"],
    }


METRIC_CELL = '''\
# Generated by `biohubx package metric-preflight`. Do not edit here.
#
# The package travels inside this notebook as a deterministic archive, verified
# against its digest before extraction. The wheelhouse is located by the identity
# carried here and verified before pip reads it. Then the five metric checks run
# from inside the verified package and write metric-preflight.json.
import base64
import hashlib
import io
import json
import os
import pathlib
import subprocess
import sys
import zipfile


def stage(name, detail=""):
    print(("BIOHUBX_STAGE " + name + " " + str(detail)).rstrip(), flush=True)


__TREE_VERIFIER__

PAYLOAD_SHA256 = "__PAYLOAD_SHA256__"
PAYLOAD_B64 = """__PAYLOAD_B64__"""
SPEC = json.loads(r"""__SPEC_JSON__""")
WHEELHOUSE_EXPECTED = json.loads(r"""__WHEELHOUSE_JSON__""")
INPUT_ROOT = pathlib.Path(os.environ.get("BIOHUBX_INPUT_ROOT", "__INPUT_ROOT__"))

stage("bootstrap-verify", "expecting " + PAYLOAD_SHA256[:23])
payload = base64.b64decode("".join(PAYLOAD_B64.split()))
actual = hashlib.sha256(payload).hexdigest()
if actual != PAYLOAD_SHA256:
    raise SystemExit("embedded package digest mismatch: expected " + PAYLOAD_SHA256 + " got " + actual)
stage("bootstrap-verify", "ok bytes=" + str(len(payload)))

target = pathlib.Path(os.environ.get("BIOHUBX_PACKAGE_ROOT", "__PACKAGE_ROOT__"))
target.mkdir(parents=True, exist_ok=True)
extracted = target / "src" / "biohubx"
with zipfile.ZipFile(io.BytesIO(payload)) as archive:
    names = archive.namelist()
    for name in names:
        if name.startswith("/") or ".." in pathlib.PurePosixPath(name).parts:
            raise SystemExit("refusing an archive entry that escapes its root: " + name)
    archive.extractall(extracted)
stage("bootstrap-extract", str(extracted) + " files=" + str(len(names)))

stage("wheelhouse", "searching " + str(INPUT_ROOT) + " for the authorised tree")
wheelhouse_root, wheelhouse_misses, wheelhouse_hashed = biohubx_find_wheelhouse(
    INPUT_ROOT, WHEELHOUSE_EXPECTED
)
if wheelhouse_root is None:
    stage("wheelhouse", "NOT FOUND expected=" + WHEELHOUSE_EXPECTED["tree"])
    for entry in biohubx_listing(INPUT_ROOT)[:40]:
        stage("wheelhouse", "mounted " + entry)
    for path_seen, token_seen, _ in wheelhouse_misses:
        stage("wheelhouse", "near miss " + path_seen + " observed=" + token_seen)
    raise SystemExit("the authorised wheelhouse is not mounted under " + str(INPUT_ROOT))
stage("wheelhouse", "resolved " + str(wheelhouse_root))

stage("wheelhouse-verify", "recomputing the mounted tree under canonicalization v1")
observed_tree, observed_records = biohubx_canonical_tree(wheelhouse_root)
wheelhouse_differences = biohubx_compare(
    [tuple(item) for item in WHEELHOUSE_EXPECTED["records"]], observed_records
)
stage("wheelhouse-verify", "expected=" + WHEELHOUSE_EXPECTED["tree"])
stage("wheelhouse-verify", "observed=" + observed_tree)
for difference in wheelhouse_differences[:20]:
    stage("wheelhouse-verify", "difference " + difference)
if observed_tree != WHEELHOUSE_EXPECTED["tree"] or wheelhouse_differences:
    raise SystemExit("the mounted wheelhouse is not the authorised published payload")
stage("wheelhouse-verify", "the mounted tree is the authorised published payload")

install_command = [
    sys.executable, "-m", "pip", "install",
    "--no-index", "--no-deps", "--require-hashes",
    "-r", str(wheelhouse_root / "requirements-offline.txt"),
    "--find-links", str(wheelhouse_root / "wheels"),
]
if os.environ.get("BIOHUBX_SKIP_INSTALL") == "1":
    stage("wheelhouse-install", "SKIPPED by BIOHUBX_SKIP_INSTALL; local gate only, NOT an install")
else:
    stage("wheelhouse-install", "offline, no index, no deps, hashes required")
    install = subprocess.run(install_command, capture_output=True, text=True, check=False)
    stage("wheelhouse-install", "returncode=" + str(install.returncode))
    if install.returncode != 0:
        print(install.stderr[-3000:], flush=True)
        raise SystemExit("the offline wheelhouse install failed")

sys.path.insert(0, str(target / "src"))
import biohubx

origin = pathlib.Path(biohubx.__file__).resolve()
if not str(origin).startswith(str(extracted.resolve())):
    raise SystemExit("biohubx was imported from " + str(origin) + ", not the verified payload")
stage("bootstrap-import", str(origin))

from biohubx.packaging.metric_preflight_runtime import run

run(SPEC, wheelhouse_root=str(wheelhouse_root), package_dir=str(extracted))
'''


def build_metric_preflight_notebook(
    shipped: dict[str, Any],
    *,
    payload: bytes,
    wheelhouse_payload: dict[str, Any],
    package_root: str = DEFAULT_PACKAGE_ROOT,
    input_root: str = INPUT_ROOT_DEFAULT,
) -> dict[str, Any]:
    """One cell carrying the package, the wheelhouse identity, and the local baseline.

    ``shipped`` is the spec with the baseline the target must reproduce. A spec
    without a baseline is refused: a preflight that measured the target without
    anything to compare against would report numbers and prove nothing.
    """
    check_payload_contents(payload)
    baseline = shipped.get("baseline") or {}
    for key in ("fixtures_digest", "real_data", "official_source", "shipped_versions"):
        if not baseline.get(key):
            raise PackagingError(
                f"the spec carries no baseline {key!r}; there would be nothing to compare against"
            )
    token = str(wheelhouse_payload.get("tree", ""))
    records = wheelhouse_payload.get("records") or []
    if not token.startswith("tree_sha256:sha256/v1:"):
        raise PackagingError(f"the wheelhouse identity must be a canonical tree token, got {token!r}")
    if not records:
        raise PackagingError("the wheelhouse identity carries no records, so a mismatch could name no file")
    source = (
        METRIC_CELL.replace("__TREE_VERIFIER__", TREE_VERIFIER_SOURCE)
        .replace("__PAYLOAD_SHA256__", hashlib.sha256(payload).hexdigest())
        .replace("__PAYLOAD_B64__", encode_payload(payload))
        .replace("__PACKAGE_ROOT__", package_root)
        .replace("__SPEC_JSON__", json.dumps(shipped, sort_keys=True))
        .replace(
            "__WHEELHOUSE_JSON__",
            json.dumps({"tree": token, "records": [list(record) for record in records]}, sort_keys=True),
        )
        .replace("__INPUT_ROOT__", input_root)
    )
    return {
        "cells": [
            {
                "id": "biohubx-metric-preflight",
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": source.splitlines(keepends=True),
            }
        ],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
