"""H1-T — provenance-preserving EXTERNAL division event set from Zebrahub tracks.

Rebuilds the external training surface the earlier `divevents_extract.py` threw away. That
extraction emitted scale-free mother-centric trajectories with "no absolute coordinates, no
embryo id" by design, so its tensors could never be joined back to imagery, to a proposer, or
to anything else. This script keeps every join key.

Two properties make this set usable where the previous one was not:

1. HARD NEGATIVES COME FROM THE DEPLOYED PROPOSER.  The candidate surface is generated by
   importing `phaseb_h0c_replay.shortlist` verbatim (frozen config hash 04eeac97500d:
   parent <= 15 um, sister <= 15 um, kNN flow k=16/min=4, rank by flow-midpoint residual,
   top-3 per mother).  Nothing is retuned.  The old negatives were "genuine continuation +
   nearby fake second daughter", a distribution the deployment proposer never emits.

2. THE GRAPH THE PROPOSER SEES IS A PREDICTION, NOT GROUND TRUTH.  Feeding the proposer the
   GT lineage would make `competing_parents`/`persist`/`mother_track_age` trivially separate
   positives (a true daughter pair would already be wired to its mother), whereas on the
   competition side 97% of shortlist rows require stealing a parent.  So a GT-FREE one-to-one
   linker is run first (greedy flow-corrected assignment, in-degree <= 1, out-degree <= 1,
   gate = E0c's inherited 10.5 um migration cap) and the GT tracks are used ONLY for labels.

UNITS (documented, not fitted):
  ZSNS003/004/005 track coordinates are LEVEL-0 VOXELS -> multiplied by the OME-Zarr
  `coordinateTransformations` scale (z 1.24, y 0.439, x 0.439 um) published in
  `<embryo>.ome.zarr/.zattrs`.
  ZSNS001 track coordinates are ALREADY MICRONS (its extent 527/927/1043 um matches the
  level-0 array 448x2174x2423 at that scale; the voxel reading would exceed the array).
  Verified by `--check-units`.

LABELS mirror `phaseb_h1a_census.py` exactly:
  positive           mother's GT track divides at t and this pair is its true daughter pair
  reliable_negative  mother's GT track continues (out-degree 1), or divides but wrong pair
  unlabeled          mother's GT track ends at t (out-degree 0)
  metric_visible     out-degree >= 1

Usage:
  .venv\\Scripts\\python.exe scripts\\win_bet\\h1t_zebrahub_events.py --check-units
  .venv\\Scripts\\python.exe scripts\\win_bet\\h1t_zebrahub_events.py --prep
  .venv\\Scripts\\python.exe scripts\\win_bet\\h1t_zebrahub_events.py --build --workers 6
"""
from __future__ import annotations

import argparse
import json
import sys
import warnings
from collections import Counter
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import numpy as np

warnings.filterwarnings("ignore")
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import polars as pl  # noqa: E402

from phaseb_h0c_replay import CFG, CFG_HASH, shortlist  # noqa: E402

RAW = ROOT / "data" / "external" / "zebrahub"
SCRATCH = Path(r"C:\Users\aryaa\Documents\Biohub-CellTracking-2026_RESEARCH\agent_runs\agent4")
PREP = SCRATCH / "zebrahub_prep"
EVENTS = SCRATCH / "external_events"
EPS = 1e-9

# OME-Zarr level-0 scale published at
# https://public.czbiohub.org/royerlab/zebrahub/imaging/single-objective/<E>.ome.zarr/.zattrs
ZARR_SCALE_UM = (1.24, 0.439, 0.439)
# level-0 array shapes (z, y, x) from <E>.ome.zarr/0/.zarray
L0_SHAPE = {"ZSNS001": (448, 2174, 2423), "ZSNS003": (258, 1929, 2038),
            "ZSNS004": (294, 1926, 2581), "ZSNS005": (291, 1910, 2750)}
# resolved by --check-units; "voxel" -> multiply by ZARR_SCALE_UM, "um" -> already microns
COORD_SPACE = {"ZSNS001": "um", "ZSNS003": "voxel", "ZSNS004": "voxel", "ZSNS005": "voxel"}

# GT-free linker. 10.5 um is E0c's inherited migration/motion-relink cap (the
# `geometric_core` parent cap in phaseb_d0p_proposer). It is NOT tuned here.
LINK_GATE_UM = 10.5
LINK_KNN = 16

EMBRYOS = ["ZSNS001", "ZSNS003", "ZSNS004", "ZSNS005"]
WINDOW = 60          # frames per shard; competition crops are 100 frames
STRIDE_WINDOWS = 3   # windows sampled per embryo, spread across the movie


def _scale_of(embryo: str) -> np.ndarray:
    return (np.array(ZARR_SCALE_UM) if COORD_SPACE[embryo] == "voxel"
            else np.array([1.0, 1.0, 1.0]))


# --------------------------------------------------------------------------------------
# prep: one compact parquet per embryo so workers get predicate pushdown
# --------------------------------------------------------------------------------------
def prep() -> None:
    PREP.mkdir(parents=True, exist_ok=True)
    for e in EMBRYOS:
        src = RAW / f"{e}_tracks.csv"
        out = PREP / f"{e}.parquet"
        if out.exists():
            print(f"  {e}: cached {out}")
            continue
        lf = pl.scan_csv(src).select(["track_id", "t", "z", "y", "x", "parent_track_id"])
        lf.sink_parquet(out)
        print(f"  {e}: -> {out}")


def check_units() -> dict:
    """Decide voxel-vs-micron per embryo from the published level-0 array extent."""
    rep = {}
    for e in EMBRYOS:
        df = pl.scan_parquet(PREP / f"{e}.parquet").select(["z", "y", "x"]).max().collect()
        mx = np.array([df["z"][0], df["y"][0], df["x"][0]], float)
        shp = np.array(L0_SHAPE[e], float)
        um_extent = shp * np.array(ZARR_SCALE_UM)
        fits_voxel = bool(np.all(mx <= shp * 1.02))
        fits_um = bool(np.all(mx <= um_extent * 1.02))
        rep[e] = {"track_max_zyx": mx.tolist(), "l0_shape": shp.tolist(),
                  "l0_extent_um": um_extent.tolist(), "fits_as_voxel": fits_voxel,
                  "fits_as_um": fits_um, "assumed": COORD_SPACE[e]}
        print(f"  {e}: max={mx.round(1).tolist()} l0_voxels={shp.tolist()} "
              f"l0_um={um_extent.round(0).tolist()} voxel_ok={fits_voxel} um_ok={fits_um} "
              f"-> assumed {COORD_SPACE[e]}")
    return rep


# --------------------------------------------------------------------------------------
# GT-free pseudo-prediction linker
# --------------------------------------------------------------------------------------
def pseudo_link(t: np.ndarray, pos: np.ndarray) -> list[tuple[int, int]]:
    """Greedy flow-corrected one-to-one linking. Never sees GT lineage.

    Two passes per frame pair: pass A is plain nearest-neighbour, used only to estimate a
    local kNN flow; pass B assigns greedily on |target - (source + flow)| within the gate,
    enforcing in-degree <= 1 and out-degree <= 1 (E0c's structure).
    """
    from scipy.spatial import cKDTree
    by_t: dict[int, np.ndarray] = {}
    for i, a in enumerate(t):
        by_t.setdefault(int(a), []).append(i)
    by_t = {a: np.asarray(v) for a, v in by_t.items()}

    edges: list[tuple[int, int]] = []
    for a in sorted(by_t):
        s_idx, d_idx = by_t.get(a), by_t.get(a + 1)
        if d_idx is None or len(s_idx) == 0 or len(d_idx) == 0:
            continue
        S, D = pos[s_idx], pos[d_idx]
        dtree = cKDTree(D)
        # pass A: nearest neighbour displacement field
        dist0, j0 = dtree.query(S, k=1)
        ok = dist0 <= LINK_GATE_UM
        if ok.sum() >= 4:
            src_ok = S[ok]
            disp = D[j0[ok]] - src_ok
            ktree = cKDTree(src_ok)
            kk = min(LINK_KNN, len(src_ok))
            _, jj = ktree.query(S, k=kk)
            jj = np.atleast_2d(jj)
            flow = np.median(disp[jj], axis=1)
        else:
            flow = np.zeros_like(S)
        # pass B: greedy assignment on flow-corrected residual
        pred = S + flow
        cand = dtree.query_ball_point(pred, LINK_GATE_UM)
        pairs = []
        for i, cl in enumerate(cand):
            if not cl:
                continue
            cl = np.asarray(cl)
            r = np.linalg.norm(D[cl] - pred[i], axis=1)
            for c, rr in zip(cl, r):
                pairs.append((float(rr), i, int(c)))
        pairs.sort()
        used_s, used_d = set(), set()
        for _, i, c in pairs:
            if i in used_s or c in used_d:
                continue
            used_s.add(i)
            used_d.add(c)
            edges.append((int(s_idx[i]), int(d_idx[c])))
    return edges


# --------------------------------------------------------------------------------------
# feature block — byte-for-byte mirror of phaseb_h1g_features.features_one
# --------------------------------------------------------------------------------------
def _unit(v):
    n = float(np.linalg.norm(v))
    return v / n if n > 1e-9 else np.zeros(3)


def h1g_features(sub, t, pos, edges, cand_rows: list[dict]) -> pl.DataFrame:
    """Identical geometry/kinematics block to H1-G, so external and competition rows are
    drawn in the same feature space. `cand_rows` needs cand_id/mother/d1/d2/rank/label/
    metric_visible/flow_midpoint_residual/steal_required plus any passthrough columns."""
    from scipy.spatial import cKDTree
    from phaseb_d0p_proposer import _continuations
    idx = {int(s): i for i, s in enumerate(sub)}
    parent_of, children_of = {}, {}
    for a, b in edges:
        parent_of[int(b)] = int(a)
        children_of.setdefault(int(a), set()).add(int(b))
    by_t: dict[int, list[int]] = {}
    for i, a in enumerate(t):
        by_t.setdefault(int(a), []).append(i)
    trees = {a: cKDTree(pos[ii]) for a, ii in by_t.items()}
    lo, hi = pos.min(axis=0), pos.max(axis=0)

    cont = _continuations(edges, idx, t, pos)
    alld = [d for f in cont.values() for d in f[1]]
    gmed = np.median(np.stack(alld), axis=0) if alld else np.zeros(3)
    fmed, ktree, darr = {}, {}, {}
    for a, (s_, d_) in cont.items():
        darr[a] = np.stack(d_) if d_ else None
        fmed[a] = np.median(darr[a], axis=0) if d_ else gmed
        ktree[a] = cKDTree(pos[s_]) if len(s_) >= 4 else None
        trees.setdefault(a, None)

    def flow_at(i, a):
        kt = ktree.get(a)
        if kt is not None:
            _, jj = kt.query(pos[i], k=min(16, darr[a].shape[0]))
            return np.median(darr[a][np.atleast_1d(jj)], axis=0)
        return fmed.get(a, gmed)

    def track_age(m):
        n, cur, seen = 0, m, set()
        while cur in parent_of and cur not in seen and n < 64:
            seen.add(cur)
            cur = parent_of[cur]
            n += 1
        return n

    rows = []
    for r in cand_rows:
        m, d1, d2 = int(r["mother"]), int(r["d1"]), int(r["d2"])
        im, i1, i2 = idx.get(m), idx.get(d1), idx.get(d2)
        if im is None or i1 is None or i2 is None:
            continue
        a = int(t[im])
        pm, p1, p2 = pos[im], pos[i1], pos[i2]
        mid = 0.5 * (p1 + p2)
        fl = flow_at(im, a)
        pd1 = float(np.linalg.norm(p1 - pm))
        pd2 = float(np.linalg.norm(p2 - pm))
        sis = float(np.linalg.norm(p2 - p1))
        par = parent_of.get(m)
        mv = pm - pos[idx[par]] if par is not None and par in idx else np.zeros(3)
        u1, u2 = _unit(p1 - pm), _unit(p2 - pm)
        out = dict(r)
        out.update({
            "parent_midpoint_um": float(np.linalg.norm(mid - pm)),
            "pd1_um": min(pd1, pd2), "pd2_um": max(pd1, pd2),
            "pd_ratio": min(pd1, pd2) / (max(pd1, pd2) + 1e-9),
            "sister_um": sis,
            "cos_daughter_axis": float(np.dot(_unit(p2 - p1), _unit(mv))),
            "cos_split_vs_flow": float(np.dot(_unit(mid - pm), _unit(fl))),
            "daughter_angle": float(np.dot(u1, u2)),
            "persist_d1": int(d1 in children_of), "persist_d2": int(d2 in children_of),
            "n_persist": int(d1 in children_of) + int(d2 in children_of),
            "mother_track_age": track_age(m),
            "mother_speed_um": float(np.linalg.norm(mv)),
            "vel_consistency": float(np.linalg.norm(mv - fl)) if par is not None else -1.0,
            "local_density_t": len(trees[a].query_ball_point(pm, 15.0)) if trees.get(a) is not None else 0,
            "local_density_t1": len(trees[a + 1].query_ball_point(mid, 15.0)) if trees.get(a + 1) is not None else 0,
            "competing_parents": int(parent_of.get(d1, m) != m) + int(parent_of.get(d2, m) != m),
            "bdist_um": float(min(np.min(pm - lo), np.min(hi - pm))),
        })
        rows.append(out)
    if not rows:
        return pl.DataFrame()
    df = pl.DataFrame(rows)
    df = df.with_columns([
        pl.col("flow_midpoint_residual").min().over("mother").alias("_best"),
        pl.col("flow_midpoint_residual").sort().over("mother").shift(-1).alias("_next"),
    ])
    return df.with_columns([
        (pl.col("flow_midpoint_residual") - pl.col("_best")).alias("resid_gap_to_best"),
        (pl.col("flow_midpoint_residual") / (pl.col("_best") + 1e-9)).alias("resid_ratio"),
        (pl.col("_next") - pl.col("flow_midpoint_residual")).fill_null(-1.0).alias("best_alt_gap"),
    ]).drop("_best", "_next")


# --------------------------------------------------------------------------------------
# one shard = one (embryo, time window)
# --------------------------------------------------------------------------------------
def build_shard(args) -> dict:
    embryo, t_lo, t_hi = args
    import sys as _sys
    _sys.path.insert(0, str(ROOT / "src"))
    _sys.path.insert(0, str(Path(__file__).resolve().parent))

    df = (pl.scan_parquet(PREP / f"{embryo}.parquet")
          .filter((pl.col("t") >= t_lo) & (pl.col("t") < t_hi))
          .sort(["t", "track_id"]).collect())
    if df.height == 0:
        return {"embryo": embryo, "t_lo": t_lo, "rows": 0}

    n = df.height
    sub = np.arange(n, dtype=np.int64)                 # node id == row index in the shard
    t = df["t"].to_numpy().astype(np.int64)
    raw = df.select(["z", "y", "x"]).to_numpy().astype(float)
    pos = raw * _scale_of(embryo)
    tid = df["track_id"].to_numpy().astype(np.int64)
    ptid = df["parent_track_id"].to_numpy().astype(np.int64)

    # ---- GT-free prediction graph --------------------------------------------------
    edges = pseudo_link(t, pos)

    # ---- frozen proposer, imported verbatim ----------------------------------------
    prop, n_pre = shortlist(sub, t, pos, edges)

    # ---- GT lineage: only now, and only for labels ---------------------------------
    node_of = {(int(a), int(b)): i for i, (a, b) in enumerate(zip(tid, t))}   # (track,t)->node
    last_t: dict[int, int] = {}
    first_t: dict[int, int] = {}
    for k, a in zip(tid.tolist(), t.tolist()):
        if a > last_t.get(k, -1):
            last_t[k] = a
        if a < first_t.get(k, 1 << 30):
            first_t[k] = a
    children_of: dict[int, list[int]] = {}
    for k, p in zip(tid.tolist(), ptid.tolist()):
        if p != -1 and k not in children_of.get(p, []):
            children_of.setdefault(p, [])
            if k not in children_of[p]:
                children_of[p].append(k)

    def gt_outdeg_and_pair(node_i: int):
        """GT out-degree of a node and, if it divides here, its true daughter node pair."""
        k, a = int(tid[node_i]), int(t[node_i])
        nxt = node_of.get((k, a + 1))
        if nxt is not None:
            return 1, None                                    # track continues
        kids = [c for c in children_of.get(k, []) if first_t.get(c) == a + 1]
        if len(kids) >= 2:
            n1, n2 = node_of.get((kids[0], a + 1)), node_of.get((kids[1], a + 1))
            if n1 is not None and n2 is not None:
                return 2, (min(n1, n2), max(n1, n2))
            return 2, None
        if len(kids) == 1:
            n1 = node_of.get((kids[0], a + 1))
            return 1, None
        return 0, None                                        # ends inside the window

    parent_node = {int(b): int(a) for a, b in edges}
    cand_rows, cnt = [], Counter()
    reachable = 0
    for m, ranked in prop.items():
        od, tp = gt_outdeg_and_pair(m)
        if tp is not None:
            reachable += 1
        visible = od >= 1
        for rank, (resid, (d1, d2)) in enumerate(ranked):
            if tp is not None and (d1, d2) == tp:
                lab = "positive"
            elif od == 1 or tp is not None:
                lab = "reliable_negative"
            else:
                lab = "unlabeled"
            cnt[lab] += 1
            cnt["metric_visible"] += int(visible)
            p1, p2 = parent_node.get(d1, -1), parent_node.get(d2, -1)
            steal = int((p1 not in (-1, m)) or (p2 not in (-1, m)))
            cnt["steal_required"] += steal
            cand_rows.append({
                "embryo": embryo, "t_lo": t_lo, "t": int(t[m]),
                "mother": int(m), "d1": int(d1), "d2": int(d2), "rank": rank,
                "cand_id": f"{embryo}:{t_lo}:{m}:{d1}:{d2}",
                "mother_track_id": int(tid[m]), "d1_track_id": int(tid[d1]),
                "d2_track_id": int(tid[d2]),
                "mother_z_raw": float(raw[m, 0]), "mother_y_raw": float(raw[m, 1]),
                "mother_x_raw": float(raw[m, 2]),
                "mother_z_um": float(pos[m, 0]), "mother_y_um": float(pos[m, 1]),
                "mother_x_um": float(pos[m, 2]),
                "d1_z_um": float(pos[d1, 0]), "d1_y_um": float(pos[d1, 1]),
                "d1_x_um": float(pos[d1, 2]),
                "d2_z_um": float(pos[d2, 0]), "d2_y_um": float(pos[d2, 1]),
                "d2_x_um": float(pos[d2, 2]),
                "flow_midpoint_residual": float(resid),
                "label": lab, "metric_visible": bool(visible),
                "mother_gt_outdeg": int(od), "steal_required": bool(steal),
                "cfg_hash": CFG_HASH, "coord_space": COORD_SPACE[embryo],
            })

    out = h1g_features(sub, t, pos, edges, cand_rows)
    EVENTS.mkdir(parents=True, exist_ok=True)
    if out.height:
        out.write_parquet(EVENTS / f"{embryo}_{t_lo:04d}.parquet")

    # ---- linker fidelity vs GT (domain-gap diagnostic, not used for training) -------
    gt_edge = set()
    for i in range(n):
        k, a = int(tid[i]), int(t[i])
        j = node_of.get((k, a + 1))
        if j is not None:
            gt_edge.add((i, j))
        else:
            for c in children_of.get(k, []):
                if first_t.get(c) == a + 1 and (c, a + 1) in node_of:
                    gt_edge.add((i, node_of[(c, a + 1)]))
    pred = set(edges)
    inter = len(pred & gt_edge)
    return {"embryo": embryo, "t_lo": t_lo, "t_hi": t_hi, "nodes": n,
            "rows": out.height, "mothers": len(prop), "cand_pre_topk": n_pre,
            "reachable": reachable, "positives": cnt["positive"],
            "reliable_negatives": cnt["reliable_negative"], "unlabeled": cnt["unlabeled"],
            "metric_visible": cnt["metric_visible"], "steal_required": cnt["steal_required"],
            "pred_edges": len(pred), "gt_edges": len(gt_edge),
            "link_precision": inter / max(len(pred), 1),
            "link_recall": inter / max(len(gt_edge), 1)}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--prep", action="store_true")
    ap.add_argument("--check-units", action="store_true")
    ap.add_argument("--build", action="store_true")
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--embryos", type=str, default=",".join(EMBRYOS))
    ap.add_argument("--window", type=int, default=WINDOW)
    ap.add_argument("--windows", type=int, default=STRIDE_WINDOWS)
    a = ap.parse_args()

    if a.prep:
        prep()
    if a.check_units:
        rep = check_units()
        (SCRATCH / "unit_check.json").write_text(json.dumps(rep, indent=2))
    if not a.build:
        return

    print(f"H1-T external events on FROZEN H0c surface (cfg {CFG_HASH}): {CFG}")
    print(f"  GT-free linker: greedy flow-corrected one-to-one, gate {LINK_GATE_UM} um, k={LINK_KNN}")
    tasks = []
    for e in a.embryos.split(","):
        tmax = int(pl.scan_parquet(PREP / f"{e}.parquet").select(pl.col("t").max()).collect()[0, 0])
        # windows spread across the movie, avoiding the first/last 10%
        lo, hi = int(0.10 * tmax), int(0.90 * tmax) - a.window
        for k in range(a.windows):
            t0 = lo + int(k * (hi - lo) / max(a.windows - 1, 1))
            tasks.append((e, t0, t0 + a.window))
    print(f"  {len(tasks)} shards: {tasks}")

    with ProcessPoolExecutor(max_workers=a.workers) as ex:
        res = list(ex.map(build_shard, tasks))

    agg = Counter()
    for r in res:
        if not r.get("rows"):
            continue
        print(f"  {r['embryo']} t[{r['t_lo']}:{r['t_hi']}) nodes={r['nodes']:,} "
              f"rows={r['rows']:,} mothers={r['mothers']:,} pos={r['positives']} "
              f"relneg={r['reliable_negatives']:,} vis={r['metric_visible']:,} "
              f"steal={r['steal_required']/max(r['rows'],1):.3f} "
              f"linkP={r['link_precision']:.3f} linkR={r['link_recall']:.3f}")
        for k in ("rows", "positives", "reliable_negatives", "unlabeled", "metric_visible",
                  "steal_required", "mothers", "reachable", "cand_pre_topk", "nodes"):
            agg[k] += r[k]
    print(f"\n  TOTAL rows={agg['rows']:,} positives={agg['positives']:,} "
          f"reliable_negatives={agg['reliable_negatives']:,} "
          f"metric_visible={agg['metric_visible']:,} "
          f"reachable={agg['reachable']:,} retention={agg['positives']/max(agg['reachable'],1):.3f}")
    (SCRATCH / "external_events_manifest.json").write_text(json.dumps(
        {"config": CFG, "config_hash": CFG_HASH, "link_gate_um": LINK_GATE_UM,
         "zarr_scale_um": ZARR_SCALE_UM, "coord_space": COORD_SPACE,
         "window": WINDOW, "shards": res, "totals": dict(agg)}, indent=2, default=float))
    print(f"  wrote {EVENTS} and {SCRATCH / 'external_events_manifest.json'}")


if __name__ == "__main__":
    main()
