#!/usr/bin/env python3
"""
The DB is mostly derived - harvest_kaggle.sh, ingest_repos.py and ingest_registries.py
rebuild it. But some rows exist NOWHERE else: decisions, our own analysis facts, and any
experiment logged by hand. Those are source data sitting in a gitignored binary.

This exports them to a diffable JSONL that IS tracked, and restores them after a rebuild.

    python3 tools/sync_source_rows.py export     # after any session that adds rows
    python3 tools/sync_source_rows.py import     # after rebuilding the DB from scratch
    python3 tools/sync_source_rows.py check      # CI: fail if the export is stale
"""
import json, sqlite3, sys, os, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB   = os.path.join(ROOT, "db", "biohub_base.db")
OUT  = os.path.join(ROOT, "db", "source_rows.jsonl")

# Topics regenerated by an ingester; everything else in `fact` is ours.
DERIVED_FACT_TOPICS = ("prior-campaign", "competition", "page")
# Experiments carrying one of these refs come back from an ingester.
DERIVED_EXPT_REFS   = ("levers.yaml", "failed-experiments.md", "submission:")

def rows(cx):
    """Yield every row that no ingester can regenerate."""
    q = f"""SELECT 'fact' AS tbl, topic, key, value, claim_type, confidence, quote,
                   observed_at, review_after, status
            FROM fact
            WHERE topic NOT IN ({','.join('?'*len(DERIVED_FACT_TOPICS))})
            ORDER BY topic, key"""
    cur = cx.execute(q, DERIVED_FACT_TOPICS)
    cols = [d[0] for d in cur.description]
    for r in cur.fetchall():
        yield dict(zip(cols, r))
    cur = cx.execute("SELECT 'decision' AS tbl, made_at, question, choice, rationale, status"
                     " FROM decision ORDER BY id")
    cols = [d[0] for d in cur.description]
    for r in cur.fetchall():
        yield dict(zip(cols, r))
    cond = " AND ".join(["COALESCE(source_ref,'') NOT LIKE ?"]*len(DERIVED_EXPT_REFS))
    cur = cx.execute(f"SELECT 'experiment' AS tbl, name, machine, approach, config, cv_score,"
                     f" lb_public, lb_private, runtime_min, outcome, notes, source_ref"
                     f" FROM experiment WHERE {cond} ORDER BY name",
                     tuple(x+"%" for x in DERIVED_EXPT_REFS))
    cols = [d[0] for d in cur.description]
    for r in cur.fetchall():
        yield dict(zip(cols, r))

def export():
    cx = sqlite3.connect(DB)
    rs = list(rows(cx)); cx.close()
    with open(OUT, "w") as f:
        f.write(f"# source-only rows - no ingester regenerates these. "
                f"exported {datetime.date.today().isoformat()}\n")
        for r in rs:
            f.write(json.dumps(r, sort_keys=True, ensure_ascii=False) + "\n")
    by = {}
    for r in rs: by[r["tbl"]] = by.get(r["tbl"], 0) + 1
    print(f"exported {len(rs)} rows -> db/source_rows.jsonl   {by}")
    return rs

def load():
    if not os.path.exists(OUT):
        print("no export to import", file=sys.stderr); return 1
    cx = sqlite3.connect(DB); n = 0
    for line in open(OUT):
        if line.startswith("#") or not line.strip(): continue
        r = json.loads(line); t = r.pop("tbl")
        cols = list(r)
        cx.execute(f"INSERT OR REPLACE INTO {t} ({','.join(cols)})"
                   f" VALUES ({','.join('?'*len(cols))})", [r[c] for c in cols])
        n += 1
    cx.commit(); cx.close()
    print(f"restored {n} source rows into the DB")
    return 0

def check():
    """Non-destructive: does the tracked export match what is in the DB right now?"""
    cx = sqlite3.connect(DB); live = [json.dumps(r, sort_keys=True, ensure_ascii=False) for r in rows(cx)]; cx.close()
    if not os.path.exists(OUT):
        print("STALE: db/source_rows.jsonl does not exist", file=sys.stderr); return 1
    saved = [l.rstrip("\n") for l in open(OUT) if not l.startswith("#") and l.strip()]
    if saved == live:
        print(f"up to date ({len(live)} source rows)"); return 0
    print(f"STALE: DB has {len(live)} source rows, export has {len(saved)}."
          f" Run: python3 tools/sync_source_rows.py export", file=sys.stderr)
    return 1

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "export"
    sys.exit({"export": lambda: (export(), 0)[1], "import": load, "check": check}[cmd]())
